# Generated by Django 3.2.9 on 2021-11-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_name', models.CharField(max_length=128)),
                ('instructor_name', models.CharField(max_length=30)),
                ('syllabus_file', models.FileField(upload_to='files')),
            ],
        ),
    ]
