# Generated by Django 3.2.9 on 2021-12-04 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_file'),
        ('core', '0005_instructor'),
    ]

    operations = [
    ]
