# Generated by Django 3.2.9 on 2021-12-07 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211118_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='office_loc',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='school_list',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='syllabus_list',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_list',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_ID',
        ),
        migrations.RemoveField(
            model_name='student',
            name='syllabus_list',
        ),
    ]
