# Generated by Django 3.2.9 on 2021-12-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211207_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syllabus',
            options={'verbose_name_plural': 'Syllabi'},
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='course',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='instructor',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='course_id',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='course_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='instructor_email',
            field=models.EmailField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='instructor_name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
